MainApp/urls.py
# Django Imports
from django.urls import path

# In App Imports
from MainApp.views import CSVFileCreateView, CSVFileDetailView, CSVFileListView


app_name = 'MainApp'

urlpatterns = [
    path('csvfile/list', CSVFileListView.as_view(), name='csvfile_list'),
    path('csvfile/create', CSVFileCreateView.as_view(), name='csvfile_create'),
    path('csvfile/<int:pk>/detail', CSVFileDetailView.as_view(), name='csvfile_detail')
]

TradingProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
]


# For User Uploaded Media Files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# For staticfiles
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MainApp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import FileExtensionValidator

# Create your models here.

# ---------------------------------------------------------------------------- #
#                                    CSVFile                                   #
# ---------------------------------------------------------------------------- #

class CSVFile(models.Model):
    """
    To get the CSV File and store it
    """ 
    csv_file = models.FileField(
        _('CSV File'),
        upload_to = 'csvfiles/',
        validators = [FileExtensionValidator(['csv'])],
        help_text = "Please upload only .csv file"
    )
    
    timeframe = models.IntegerField(
        _('Timeframe'),
        blank = True,
        null = True,
        help_text = 'Please enter the timefram in minutes and should be grater than 1 minute'
    )
    
    json_file = models.FileField(
        _('JSON File'),
        upload_to = 'jsonfiles/',
        validators = [FileExtensionValidator(['json'])],
        help_text = "Please upload only .json file",
        null = True,
        blank = True
    )
    
    created_at = models.DateTimeField(
        _('Created At'),
        auto_now_add = True
    )
    
    updatedAt = models.DateTimeField(
        _('Updated At'),
        auto_now = True
    )
    
    class Meta:
        ordering = ('-id', )
        
    @property
    def sys_id(self):
        str_id = str(self.id).zfill(5)
        return f"CSV{str_id}"
    
    def __str__(self):
        return self.sys_id
    
    
# ---------------------------------------------------------------------------- #
#                                  Candlestick                                 #
# ---------------------------------------------------------------------------- #

class Candlestick(models.Model):
    """
    To store the candlestick data
    """
    csv = models.ForeignKey(
        CSVFile,
        on_delete = models.CASCADE,
        verbose_name = _('CSV File'),
        related_name = 'candlestick',
    )
    
    banknifty = models.CharField(
        _('Bank Nifty'),
        max_length = 50,
        blank = True,
        null = True
    )
    
    date = models.CharField(
        _('Date'),
        max_length = 20,
        blank = True,
        null = True
    )
    
    time = models.CharField(
        _('Time'),
        max_length = 10,
        blank = True,
        null = True
    )
    
    open_value = models.FloatField(
        _('Open'),
        blank = True,
        null = True
    )

    high = models.FloatField(
        _('High'),
        blank = True,
        null = True
    )
    
    low = models.FloatField(
        _('Low'),
        blank = True,
        null = True
    )
    
    close = models.FloatField(
        _('Close'),
        blank = True,
        null = True
    )
    
    volume = models.FloatField(
        _('Volume'),
        blank = True,
        null = True
    )
    
    created_at = models.DateTimeField(
        _('Created At'),
        auto_now_add = True
    )
    
    updatedAt = models.DateTimeField(
        _('Updated At'),
        auto_now = True
    )
    
    class Meta:
        ordering = ('-id', )
        
    @property
    def sys_id(self):
        str_id = str(self.id).zfill(5)
        return f"CDL{str_id}"
    
    def __str__(self):
        return self.sys_id
    

MainApp/forms.py
# Django imports
from django import forms

# In App Imports
from MainApp.models import CSVFile


# ---------------------------------------------------------------------------- #
#                                  CSVFileForm                                 #
# ---------------------------------------------------------------------------- #

class CSVFileForm(forms.ModelForm):
    """
    Model form to create/store csv file
    """
    class Meta:
        model = CSVFile
        fields = (
            'csv_file',
            'timeframe',
        )
        
    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = True
                
    def clean(self, *args, **kwargs):
        cleaned_data = super(self.__class__, self).clean(*args, **kwargs)
        
        timeframe = cleaned_data.get('timeframe')
        if timeframe < 1:
            raise forms.ValidationError("Timeframe can not be less than 1 min")
        
        return cleaned_data
        

MainApp/views.py
# Django imports
from django.shortcuts import redirect, render
from django.views.generic import ListView, CreateView, DetailView
from django.urls import reverse_lazy
from django.conf import settings
from django.core.files import File


# python imports
import csv
import os
import json

# In app imports
from MainApp.models import CSVFile, Candlestick
from MainApp.forms import CSVFileForm


# Create your views here.

# ---------------------------------------------------------------------------- #
#                                CSVFileListView                               #
# ---------------------------------------------------------------------------- #

class CSVFileListView(ListView):
    """
    To display the list of uploaded csv files
    """
    model = CSVFile
    template_name = 'MainApp/csvfile_list.html'
    success_url = reverse_lazy('MainApp:csvfile_list')
    
    
# ---------------------------------------------------------------------------- #
#                               CSVFileCreateView                              #
# ---------------------------------------------------------------------------- #

class CSVFileCreateView(CreateView):
    """
    To upload the csv file and store timframe and create candlestick objects
    """
    model = CSVFile
    template_name = 'MainApp/csvfile_create.html'
    form_class = CSVFileForm
    success_url = reverse_lazy('MainApp:csvfile_list')
    
    def post(self, *arg, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.save()
            csv_obj = CSVFile.objects.all().first()
            timeframe = csv_obj.timeframe
            file = open(os.path.join(settings.BASE_DIR) + csv_obj.csv_file.url)
            reader = csv.DictReader(file)
            count = 0
            total_rows = 0
            
            banknifty_list = []
            date_list = []
            time_list = []
            open_list = []
            high_list = []
            low_list = []
            close_list = []
            volume_list = []
            
            count = 0
            for row in reader:
                banknifty_list.append(row['BANKNIFTY'])
                date_list.append(row['DATE'])
                time_list.append(row['TIME'])
                open_list.append(row['OPEN'])
                high_list.append(row['HIGH'])
                low_list.append(row['LOW'])
                close_list.append(row['CLOSE'])
                volume_list.append(row['VOLUME'])
                count += 1
                
                if count == timeframe:
                    count = 0
                    banknifty = banknifty_list[0]
                    date = date_list[0]
                    time = time_list[0]
                    open_value = open_list[0]
                    high = max(high_list)
                    low = min(low_list)
                    close = close_list[-1]
                    volume = volume_list[-1]
                
                    create_candlestick = Candlestick.objects.create(
                        csv = csv_obj,
                        banknifty = banknifty,
                        date = date,
                        time = time,
                        open_value = open_value,
                        high = high,
                        low = low,
                        close = close,
                        volume = volume
                    )
                    
                    banknifty_list.clear()
                    date_list.clear()
                    time_list.clear()
                    open_list.clear()
                    high_list.clear()
                    low_list.clear()
                    close_list.clear()
                    volume_list.clear()
                    
            try:
                candles_list = list(Candlestick.objects.filter(csv=csv_obj).values(
                        'csv__csv_file',
                        'banknifty',
                        'date',
                        'time',
                        'open_value',
                        'close',
                        'high',
                        'low',
                        'volume'
                    )
                )
                if len(candles_list) > 0:
                    temp_file = open(f'{csv_obj.sys_id}.json', 'w')
                    json_obj = json.dumps(candles_list)
                    temp_file.write(json_obj)
                    temp_file.close()
                    temp_file = open(f'{csv_obj.sys_id}.json')
                    csv_obj.json_file.save(f"{csv_obj.sys_id}.json", File(temp_file))
                    temp_file.close()
                    os.remove(os.path.abspath(temp_file.name)) 
            except:
                pass
                    
        return redirect(self.success_url)
    
    
# ---------------------------------------------------------------------------- #
#                               CSVFileDetailView                              #
# ---------------------------------------------------------------------------- #


class CSVFileDetailView(DetailView):
    """
    To display the list of uploaded csv files
    """
    model = CSVFile
    template_name = 'MainApp/csvfile_detail.html'
    success_url = reverse_lazy('MainApp:csvfile_list')
    extra_context = {}
    
    def get_queryset(self, *args, **kwargs):
        queryset = super(self.__class__, self).get_queryset(*args, **kwargs)
        candles = Candlestick.objects.filter(csv_id=self.kwargs['pk'])
        self.extra_context = {'candles': candles}
        return queryset
                    
            

MainApp/templates/MainApp/csvfile_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<title>Upload CSV File</title>

<div class="container text-center">
    <div class="col-12 mt-4">
        <h3>Upload CSV File</h3>
    </div>

    <div class="form-control mt-4" >
        <form method="post" class="my-class" enctype="multipart/form-data">
            {{ form|crispy }}
            {% csrf_token %}
                <button type="button" onclick="history.back();" value="cancel" class="btn btn-secondary">Cancel</button>
                <button type="submit" class="btn btn-success" value="submit">Submit</button>
            </div>
        </form>
    </div>
    
</div>



{% endblock content %}

MainApp/templates/MainApp/csvfile_detail.html
{% extends 'base.html' %}


{% block content %}
<title>Candlesticks</title>

<div class="container text-center mt-4">
    <div class="row">
        <div class="col-3">
            <a target="_blank" class="anchor-secondary py-4" href="{% url 'MainApp:csvfile_list' %} "><i class="fas fa-file fa-2x mb-2" aria-hidden="true"></i>View CSV List</a>
        </div>
        <div class="col-6">
            <h3>Candlesticks - {{object}} </h3>
        </div>
        <div class="col-3">
            {% if object.json_file %}
                <a target="_blank" class="anchor-secondary py-4" href="{{ object.json_file.url }}"><i class="fas fa-file fa-2x mb-2" aria-hidden="true"></i>Download JSON File</a>
            {% else %}
                <a target="_blank" class="anchor-secondary py-4" href="#"><i class="fas fa-file fa-2x mb-2" aria-hidden="true" disabled></i>No JSON File</a>
            {% endif %}
        </div>
    </div>

    <table class="table table-hover mt-5 table-bordered">
        <thead class="table-dark">
            <tr>
                <th scope="col">Sys ID</th>
                <th scope="col">Nifty</th>
                <th scope="col">Open</th>
                <th scope="col">High</th>
                <th scope="col">Low</th>
                <th scope="col">Close</th>
                <th scope="col">Volume</th>
            </tr>
        </thead>
        <tbody>
            {% for candle in candles %}
                <tr>
                    <td> {{candle.sys_id}} </td>
                    <td> {{candle.banknifty}} </td>
                    <td> {{candle.open_value}} </td>
                    <td> {{candle.high}} </td>
                    <td> {{candle.low}} </td>
                    <td> {{candle.close}} </td>
                    <td> {{candle.volume}} </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock content %}

MainApp/templates/MainApp/csvfile_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container text-center" >
    <title>CSV File List</title>
</div>

<div class="container text-center mt-4 mb-4">
    <div class="row">
        <div class="col-8">
            <h3>CSV File List</h3>
        </div>
        <div class="col-4">
            <a href="{% url 'MainApp:csvfile_create' %}"> <button type="button" class="btn btn-primary">Upload CSV</button></a>
        </div>
    </div>
    
    <br><br>

    <table class="table table-hover">
        <thead class="table-dark">
            <tr>
                <th scope="col">Sr. No</th>
                <th scope="col">CSV File</th>
                <th scope="col">Time Frame</th>
                <th scope="col">View</th>
                <th scope="col">Download</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{object.sys_id}} </td>
                    <td><a target="_blank" class="anchor-secondary py-4" href="{{ object.csv_file.url }}">{{ object.csv_file.name }}</a></td>
                        
                    <td>{{object.timeframe}} </td>
                    <td>
                        <a target="_blank" class="anchor-secondary py-4" href="{% url 'MainApp:csvfile_detail' object.pk %}"></i>Candlesticks</a>
                    </td>
                    <td>
                        {% if object.json_file %}
                            <a target="_blank" class="anchor-secondary py-4" href="{{ object.json_file.url }}">JSON File</a>
                        {% else %}
                            <a class="anchor-secondary py-4" href="#">No JSON File</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>






{% endblock content %}