MainApp/urls.py
# Django Imports
from django.urls import path

# In App Imports
from MainApp.views import CSVFileCreateView, CSVFileDetailView, CSVFileListView


app_name = 'MainApp'

urlpatterns = [
    path('csvfile/list', CSVFileListView.as_view(), name='csvfile_list'),
    path('csvfile/create', CSVFileCreateView.as_view(), name='csvfile_create'),
    path('csvfile/<int:pk>/detail', CSVFileDetailView.as_view(), name='csvfile_detail')
]

TradingProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
]


# For User Uploaded Media Files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# For staticfiles
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">


<div class="container text-center">
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'MainApp:csvfile_list' %} ">Trading Project</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'MainApp:csvfile_list' %} ">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'MainApp:csvfile_create' %}">Upload CSV</a>
                    </li>
                    
            </div>
        </div>
    </nav>
</div>



{% block content %}


{% endblock content %}